ALTER TABLE IF EXISTS project DROP FOREIGN KEY IF EXISTS FKproject313086;
ALTER TABLE IF EXISTS user_session DROP FOREIGN KEY IF EXISTS FKuser_sessi859336;
ALTER TABLE IF EXISTS `user` DROP FOREIGN KEY IF EXISTS FKuser291107;
ALTER TABLE IF EXISTS account_session DROP FOREIGN KEY IF EXISTS FKaccount_se158343;

DROP TABLE IF EXISTS account;
DROP TABLE IF EXISTS account_session;
DROP TABLE IF EXISTS project;
DROP TABLE IF EXISTS server_settings;
DROP TABLE IF EXISTS `user`;
DROP TABLE IF EXISTS user_session;

