version: "3.8"

services:
  auth:
    container_name: jauth-auth
    image: jauth-auth:latest
    healthcheck:
      test: [ "CMD", "node", "-e", "require('http').get('http://localhost:${AUTH_PORT}/status', (r) => {if (r.statusCode !== 200) throw new Error(r.statusCode)})" ]
      timeout: 5s
      interval: 5s
      retries: 3
    ports:
      - ${AUTH_PORT}:3000/tcp
    networks:
      - jauth
    environment:
      PORT: ${AUTH_PORT}
      RSA_ENCRYPTION_SECRET: ${RSA_ENCRYPTION_SECRET}
      ALLOW_MULTIPLE_ACCOUNTS: ${ALLOW_MULTIPLE_ACCOUNTS}
      ACCOUNT_NAME: ${ACCOUNT_NAME}
      ACCOUNT_PASS: ${ACCOUNT_PASS}
      ACCOUNT_EMAIL: ${ACCOUNT_EMAIL}
      PROJECT_NAMES: ${PROJECT_NAMES}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_SCHEMA: ${DB_SCHEMA}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_URL: ${DB_URL}
      SWAGGER_USER: ${SWAGGER_USER}
      SWAGGER_PASS: ${SWAGGER_PASS}
    depends_on:
      - db

  db:
    container_name: jauth-db
    image: mariadb:latest
    restart: unless-stopped
    networks:
      - jauth
    volumes:
      - jauth-db:/var/lib/mysql:rw
    ports:
      - 3306:3306
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASS}
      MARIADB_DATABASE: ${DB_SCHEMA}
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASS}

networks:
  jauth:

volumes:
  jauth-db: